name: dotnet-setup
description: setup the dotnet environment, global tools and whatever else is needed

inputs:
  dotnet-versions:
    description: the dotnet version(s) to install and use
    required: true

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 100
        fetch-tags: true

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-versions }}
