namespace Runedur.Generator;

public static class EntityAttributeGenerationHelper
{
    public static readonly string Attribute = $@"// <auto-generated/>
namespace Runedur
{{
    /// <summary>
    /// Marks a class as an entity that Runedur should
    /// consider during code generation
    /// </summary>
    [{GeneralGenerationHelper.GeneratedCodeAttribute}]
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false)]
    internal sealed class RunedurEntityAttribute : global::System.Attribute
    {{
    }}
}}";
}