name: "PR lint"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request: 
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  pr-lint:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pr-lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
