name: pr-lint/title
description: Lint the PR title according to semantic commit rules

inputs:
  github-token:
    description: "Github token from the workflow"
    required: true

outputs: 
  error_message:
    description: Error message from the validation of the PR title
    value: ${{ steps.lint-pr-title.outputs.error_message }}

runs:
  using: "composite"
  steps:
    - name: Validate PR title
      id: lint-pr-title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        # Configure which scopes are allowed (newline-delimited).
        # These are regex patterns auto-wrapped in `^ $`.
        scopes: |
          deps-dev
          deps
          gh-\d+
          GH-\d+
        requireScope: true
